server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: INFO
    '[com.mobe.mobe_life_backend]': DEBUG
    '[org.springframework]': INFO
    '[org.springframework.web]': INFO
    '[org.mybatis]': INFO
    '[javax.management]': WARN
    '[javax.management.remote.rmi]': WARN
    '[javax.management.mbeanserver]': WARN
    '[sun.rmi]': WARN
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
file:
  upload:
    path: /Users/liukaiwen/Desktop/MoBe_Life/mobe-life-backend/uploads
    access-url-prefix: http://127.0.0.1:8080/uploads
wechat:
  miniapp:
    app-id: wx5992d0bb44379dea
    app-secret: d8989a5e2d77e9d74fae0f5ec76d3fd1
tencent:
  ses:
    secret-id: ${TENCENT_SES_SECRET_ID:}
    secret-key: ${TENCENT_SES_SECRET_KEY:}
    region: ap-hongkong
    from-email: code@triaura.icu
    from-name: MoBe 验证中心
    template-id: 172524
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
qweather:
  api-host: https://ng6apxvu47.re.qweatherapi.com
  api-key: c3c21ab925fa4cbcb9546be600153926
one:
  api-url: http://v3.wufazhuce.com:8000/api/channel/one/0/0
